### ISSUE TITLE
Distinção de Inst. Financeiras e Bancos

### ISSUE THREAD

**Issue by gsilvapt** [centraldedados/instituicoes-financeiras#2]
Tendo vindo do BP (não tive chance de olhar para o ficheiro - sorry!), quase de certeza que só contempla Bancos e Sociedades Financeiras e de Crédito. Instituições Financeiras engloba todas as empresas que mexam em dinheiro (seguradoras, brokers, etc.).

Portanto, se a ideia é manter uma lista das instituições bancárias a funcionar, então secalhar é melhor mudar o nome para não haver confusão. Se for para ter informação detalhada sobre todo o sector financeiro, então é preciso acrescentar algumas fontes - Posso ajudar em ambos se for o caso!

**Comment by rlafuente** [comment]
Boa :-) a @aiscarvalho pode esclarecer as fontes. Que nome deveria ter esta data package então? Temos usado a norma `tema-titulo_do_dataset`, como `parlamento-datas_sessoes` ou `eleicoes-legislativas`.

**Comment by gsilvapt** [comment]
Dependerá do conteúdo do dataset, a meu ver. Se o foco for os bancos, então deveria ser bancos-registos_em_pt :)

**Comment by rlafuente** [comment]
ok, concordo!

**Comment by rlafuente** [comment]
estava aqui a pensar, e se usarmos como tema o termo "finanças", que é mais abrangente que bancos? Ex. `financas-bancos_registados`

**Comment by gsilvapt** [comment]
Pode ser, parece-me bem. Assim fica o sector todo agrupado em Finanças e, se algum houver algum projecto que cubra mercados financeiros, pode ficar sob o tema de Finanças. :+1:

**Comment by rlafuente** [comment]
Feito!
